version: '3.1'
services:
    nginx:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '80:80'
        networks:
            - app-network

    php:
        build: docker/php
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
        networks:
            - app-network

    mysql:
        image: 'mysql:5.7'
        working_dir: /application
        volumes:
            - '.:/application'
            - ./docker/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=laravel
            - MYSQL_USER=laravel
            - MYSQL_PASSWORD=laravel
        ports:
            - '9002:3306'
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql
            - PMA_USER=root
            - PMA_PASSWORD=root
        links:
            - mysql
        restart: always
        networks:
            - app-network

    redis:
        image: redis
        ports:
            - "6379:6379"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

